#!/usr/bin/env python3
"""Extract the text rules Hlas for Windows shares with Hlas for macOS.

The macOS Swift sources are the single source of truth for the Smart text
prompt, the Whisper priming prompts and the hallucination blocklist. This
script reads them and either writes shared/hlas-shared.json (default) or, with
--check, fails when the committed JSON has drifted from the Swift sources.

Usage:
    python3 tools/shared_from_mac.py <path-to-hlas-macos-checkout> [--check]
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "shared" / "hlas-shared.json"


def swift_multiline(source: str, marker: str) -> str:
    """Return the value of a Swift multi-line string literal after `marker`."""
    start = source.index(marker)
    open_q = source.index('"""', start) + 3
    close_q = source.index('"""', open_q)
    body = source[source.index("\n", open_q) + 1:close_q]
    lines = body.split("\n")
    # The closing delimiter's indentation is stripped from every line.
    indent = len(lines[-1]) - len(lines[-1].lstrip(" "))
    lines = lines[:-1]
    return "\n".join(line[indent:] if line.strip() else "" for line in lines)


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    mac = Path(sys.argv[1])
    check = "--check" in sys.argv

    types = (mac / "Sources/HlasCore/DictationTypes.swift").read_text()
    halluc = (mac / "Sources/HlasCore/Hallucinations.swift").read_text()
    whisper = (mac / "Sources/Hlas/LocalWhisper.swift").read_text()
    smart = (mac / "Sources/Hlas/SmartTextProcessor.swift").read_text()

    prompt = swift_multiline(types, "public static let prompt")
    block = halluc.split("patterns: [String] = [", 1)[1].split("]", 1)[0]
    patterns = re.findall(r'"([^"]+)"', block)
    priming = dict(re.findall(r'case "(\w+)": priming = "([^"]+)"', whisper))
    sha = re.search(r'expectedSHA256 = "([0-9a-f]{64})"', whisper).group(1)
    size = int(re.search(r"modelByteCount: Int64 = ([\d_]+)", whisper).group(1).replace("_", ""))
    name = re.search(r'modelName = "([^"]+)"', whisper).group(1)
    url = re.search(r'"(https://huggingface\.co/[^"]+\.bin)"', whisper.replace("\n", "").replace('"\n', "")) or \
        re.search(r'(https://huggingface\.co/\S+?\.bin)', whisper)
    groq_smart = re.search(r'model: "(openai/[^"]+)"', smart).group(1)
    openai_smart = re.search(r'model: "(gpt-[^"]+)"', smart).group(1)

    data = {
        "_comment": "Generated by tools/shared_from_mac.py from the Hlas for macOS sources. Do not edit by hand.",
        "smart_text_prompt": prompt,
        "smart_text_models": {"groq": groq_smart, "openai": openai_smart},
        "priming_prompts": priming,
        "hallucination_patterns": patterns,
        "hallucination_ratio": 0.3,
        "model": {"file": name, "url": url.group(1), "bytes": size, "sha256": sha},
    }
    text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    if check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print("shared/hlas-shared.json has drifted from the macOS sources.")
            print("Run: python3 tools/shared_from_mac.py <mac checkout>")
            return 1
        print("shared/hlas-shared.json matches the macOS sources.")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
